services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_DATABASE=sistema_diplomas
      - DB_USER=user
      - DB_PW=userpassword
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_diplomas
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "3306:3306"

  diploma-generator:
    build: 
      context: ./DiplomaGenerator
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mysql

volumes:
      rabbitmq_data:
      mysqldata: